local CraftScan = select(2, ...)

CraftScan.CONST = {}

CraftScan.CONST.LEFT = 0
CraftScan.CONST.RIGHT = 1

---@enum CraftScan.LOCALIZATION_IDS
CraftScan.CONST.TEXT = {
    CRAFT_SCAN = 0,
    CHAT_ORDERS = 1,
    DISABLE_ADDONS = 2,
    RENABLE_ADDONS = 3,
    DISABLE_ADDONS_TOOLTIP = 4,
    GREETING_I_CAN_CRAFT_ITEM = 5,
    GREETING_ALT_CAN_CRAFT_ITEM = 6,
    GREETING_LINK_BACKUP = 7,
    GREETING_I_HAVE_PROF = 8,
    GREETING_ALT_HAS_PROF = 9,
    GREETING_ALT_SUFFIX = 10,
    MAIN_BUTTON_BINDING_NAME = 11,
    GREET_BUTTON_BINDING_NAME = 12,
    DISMISS_BUTTON_BINDING_NAME = 13,
    TOGGLE_CHAT_TOOLTIP = 14,
    SCANNER_CONFIG_SHOW = 16,
    SCANNER_CONFIG_HIDE = 17,
    CRAFT_SCAN_OPTIONS = 18,
    ITEM_SCAN_CHECK = 19,
    HELP_PROFESSION_KEYWORDS = 20,
    HELP_PROFESSION_EXCLUSIONS = 21,
    HELP_SCAN_ALL = 22,
    HELP_PRIMARY_EXPANSION = 23,
    HELP_EXPANSION_GREETING = 24,
    HELP_CATEGORY_KEYWORDS = 25,
    HELP_CATEGORY_GREETING = 26,
    HELP_CATEGORY_OVERRIDE = 27,
    HELP_ITEM_KEYWORDS = 28,
    HELP_ITEM_GREETING = 29,
    HELP_ITEM_OVERRIDE = 30,
    HELP_GLOBAL_KEYWORDS = 31,
    HELP_GLOBAL_EXCLUSIONS = 32,
    SCAN_ALL_RECIPES = 34,
    SCANNING_ENABLED = 35,
    SCANNING_DISABLED = 36,
    PRIMARY_KEYWORDS = 37,
    HELP_PRIMARY_KEYWORDS = 38,
    HELP_CATEGORY_SECTION = 39,
    HELP_EXPANSION_SECTION = 40,
    HELP_PROFESSION_SECTION = 41,
    RECIPE_NOT_LEARNED = 42,
    PING_SOUND_LABEL = 43,
    PING_SOUND_TOOLTIP = 44,
    BANNER_SIDE_LABEL = 45,
    BANNER_SIDE_TOOLTIP = 46,
    CUSTOMER_TIMEOUT_LABEL = 47,
    CUSTOMER_TIMEOUT_TOOLTIP = 48,
    BANNER_TIMEOUT_LABEL = 49,
    BANNER_TIMEOUT_TOOLTIP = 50,
    EXCLUSION_INSTRUCTIONS = 51,
    KEYWORD_INSTRUCTIONS = 52,
    GREETING_INSTRUCTIONS = 53,
    GLOBAL_INCLUSION_DEFAULT = 54,
    GLOBAL_EXCLUSION_DEFAULT = 55,
    DEFAULT_KEYWORDS_BLACKSMITHING = 56,
    DEFAULT_KEYWORDS_LEATHERWORKING = 57,
    DEFAULT_KEYWORDS_ALCHEMY = 58,
    DEFAULT_KEYWORDS_TAILORING = 59,
    DEFAULT_KEYWORDS_ENGINEERING = 60,
    DEFAULT_KEYWORDS_ENCHANTING = 61,
    DEFAULT_KEYWORDS_JEWELCRAFTING = 62,
    DEFAULT_KEYWORDS_INSCRIPTION = 63,
    ADDON_WHITELIST_LABEL = 64,
    ADDON_WHITELIST_TOOLTIP = 65,
    SCANNER_CONFIG_DISABLED = 66,
    DELETE_CONFIG_TOOLTIP_TEXT = 67,
    DELETE_CONFIG_CONFIRM = 68,
    CLEANUP_CONFIG_TOOLTIP_TEXT = 69,
    CLEANUP_CONFIG_CONFIRM = 70,
    PRIMARY_CRAFTER_TOOLTIP = 71,
    CHAT_BUTTON_BINDING_NAME = 72,
    MULTI_SELECT_BUTTON_TEXT = 73,
    ACCOUNT_LINK_DESC = 74,
    ACCOUNT_LINK_PROMPT_CHARACTER = 75,
    ACCOUNT_LINK_PROMPT_NICKNAME = 76,
    ACCOUNT_LINK_ACCEPT_DST_INFO = 79,
    LINKED_ACCOUNT_REJECTED = 80,
    VERSION_MISMATCH = 81,
    REMOTE_CRAFTER_TOOLTIP = 83,
    REMOTE_CRAFTER_SUMMARY = 84,
    LINK_ACTIVE = 85,
    ACCOUNT_LINK_DELETE_INFO = 87,
    ACCOUNT_LINK_ADD_CHAR = 88,
    CUSTOM_GREETING_INFO = 89,
    EXTRA_PLACEHOLDERS = 90,
    MISSING_PLACEHOLDERS = 91,
    LEGACY_PLACEHOLDERS = 92,
    ANALYTICS_ITEM_TOOLTIP = 93,
    ANALYTICS_PROFESSION_TOOLTIP = 94,
    ANALYTICS_TOTAL_TOOLTIP = 95,
    ANALYTICS_REPEAT_TOOLTIP = 96,
    ANALYTICS_AVERAGE_TOOLTIP = 97,
    ANALYTICS_PEAK_TOOLTIP = 98,
    ANALYTICS_MEDIAN_TOOLTIP = 99,
    ANALYTICS_MEDIAN_TOOLTIP_FILTERED = 100,
    LINKED_ACCOUNT_USER_REJECTED = 101,
    LINKED_ACCOUNT_PERMISSION_FULL = 102,
    LINKED_ACCOUNT_PERMISSION_ANALYTICS = 103,
    ACCOUNT_LINK_PERMISSIONS_DESC = 104,
    ACCOUNT_LINK_FULL_CONTROL_DESC = 105,
    ACCOUNT_LINK_ANALYTICS_DESC = 106,
    ANALYTICS_PROF_MISMATCH = 107,
    BUSY_RIGHT_NOW = 108,
    BUSY_HELP = 109,
    EXPLANATION_LABEL_DESC = 110,
    EXPLANATION_DUPLICATE_LABEL = 111,
    EXPLANATION_TEXT_DESC = 112,
    MANUAL_MATCHING_TITLE = 113,
    MANUAL_MATCH = 114,
    MANUAL_MATCHING_DESC = 115,
    SECONDARY_KEYWORD_INSTRUCTIONS = 116,
    HELP_ITEM_SECONDARY_KEYWORDS = 117,
    FOUND_CRAFTER_NAME_ENTRY = 118,
    GREET_FOUND_CRAFTER = 119,
    BUSY_ICON = 120,
    FOUND_VIA_CRAFT_SCAN = 121,
    COMMISSION_INSTRUCTIONS = 122,
    DEFAULT_COMMISSION = 123,
    HELP_ITEM_COMMISSION = 124,
    DISCOVERABLE_SETTING = 125,
    GREETING_BUSY = 126,
    PERMISSIVE_MATCH_SETTING = 127,
    SHOW_CHAT_ORDER_TAB = 128,
    IGNORE = 129,
    UNIGNORE = 130,
    IGNORE_TOOLTIP = 131,
    UNIGNORE_TOOLTIP = 132,
    COLLAPSE_CHAT_CONTEXT_TOOLTIP = 133,
    PROXY_ORDERS_TOOLTIP = 134,
    RECEIVE_PROXY_ORDERS_TOOLTIP = 135,
    CONFIG_TOGGLE_BINDING_NAME = 136,
    PENDING_REVIEW = 137,
    SCANNING_ON = 138,
    SCANNING_OFF = 139,
    UNLEARNED = 140,

    -- Release notes have multiple lines that are sequential. Spaced out by hundreds to give more than enough room.
    RN_WELCOME = 10000,
    RN_INITIAL_SETUP = 10100,
    RN_INITIAL_TESTING = 10200,
    RN_MANAGING_CRAFTERS = 10300,
    RN_MANAGING_CUSTOMERS = 10400,
    RN_KEYBINDS = 10500,
    RN_CLEANUP = 10600,
    RN_LINKED_ACCOUNTS = 10700,
    RN_ANALYTICS = 10800,
    RN_ALERT_ICON_ANCHOR = 10900,
    RN_MANUAL_MATCH = 11000,
    RN_CUSTOM_EXPLANATIONS = 11100,
    RN_BUSY_MODE = 11200,
    RN_SECONDARY_KEYWORDS = 11300,
    RN_CUSTOMER_SEARCH = 11400,
    RN_DISCORD = 11500,
    RN_CONFIG_REWORK = 11600,
    RN_SUBSTITUTION_TAGS = 11700,
}

CraftScan.CONST.DEFAULT_SETTINGS = {
    ping_sound = '12867',
    banner_direction = CraftScan.CONST.RIGHT,
    customer_timeout = 10,
    banner_timeout = 20,
    last_loaded_version = 0,
    auto_reply_delay = 500,
    disabled_addon_whitelist = 'None',
    show_button_height = 0,
    alert_icon_scale = 100,
}

CraftScan.CONST.PROFESSION_COLORS = {
    [164] = 'ffc98e64', -- BS
    [165] = 'ffffaa00', -- LW
    [171] = 'ff8900ff', -- Alc
    [197] = 'ffffff00', -- Tailoring
    [202] = 'ff30aaff', -- Eng
    [333] = 'ff3000ff', -- Enchanting
    [755] = 'ffff0066', -- JC
    [773] = 'ffffff99', -- Inscription
}

-- I can't find an API that provides profession icons unless the current
-- character knows the profession. Hate maintaining things, but  easy enough and
-- we use the parent professions as a backup.
CraftScan.CONST.PARENT_PROFESSION_ICONS = {
    [164] = 136241, -- Blacksmithing
    [165] = 136247, -- Leatherworking
    [171] = 136240, -- Alchemy
    [197] = 136249, -- Tailoring
    [202] = 136244, -- Engineering
    [333] = 136243, -- Enchanting
    [755] = 134071, -- Jewelcrafting
    [773] = 237171, -- Inscription
}

-- ExpansionUpdateTag
CraftScan.CONST.TWW_PROFESSION_ICONS = {
    [3017] = 136240, -- Alchemy
    [3021] = 136241, -- Blacksmithing
    [3034] = 136244, -- Enchanting
    [3037] = 136245, -- Engineering
    [3040] = 237171, -- Inscription
    [3043] = 134071, -- Jewelcrafting
    [3046] = 136247, -- Leatherworking
    [3049] = 136249, -- Tailoring
}

CraftScan.CONST.PROFESSION_DEFAULT_KEYWORDS = {
    [164] = CraftScan.CONST.TEXT.DEFAULT_KEYWORDS_BLACKSMITHING,
    [165] = CraftScan.CONST.TEXT.DEFAULT_KEYWORDS_LEATHERWORKING,
    [171] = CraftScan.CONST.TEXT.DEFAULT_KEYWORDS_ALCHEMY,
    [197] = CraftScan.CONST.TEXT.DEFAULT_KEYWORDS_TAILORING,
    [202] = CraftScan.CONST.TEXT.DEFAULT_KEYWORDS_ENGINEERING,
    [333] = CraftScan.CONST.TEXT.DEFAULT_KEYWORDS_ENCHANTING,
    [755] = CraftScan.CONST.TEXT.DEFAULT_KEYWORDS_JEWELCRAFTING,
    [773] = CraftScan.CONST.TEXT.DEFAULT_KEYWORDS_INSCRIPTION,
}

CraftScan.CONST.DEFAULT_PPCONFIG = {
    scanning_enabled = true,
    visual_alert_enabled = true,
    sound_alert_enabled = false,
}

CraftScan.CONST.RECIPE_STATES = {
    PENDING_REVIEW = 1,
    SCANNING_ON = 2,
    SCANNING_OFF = 3,
    UNLEARNED = 4,
}

CraftScan.CONST.RECIPE_STATE_NAMES = {
    [CraftScan.CONST.RECIPE_STATES.PENDING_REVIEW] = CraftScan.CONST.TEXT.PENDING_REVIEW,
    [CraftScan.CONST.RECIPE_STATES.SCANNING_ON] = CraftScan.CONST.TEXT.SCANNING_ON,
    [CraftScan.CONST.RECIPE_STATES.SCANNING_OFF] = CraftScan.CONST.TEXT.SCANNING_OFF,
    [CraftScan.CONST.RECIPE_STATES.UNLEARNED] = CraftScan.CONST.TEXT.UNLEARNED,
}
